version: "3.7"

services:
  whoami:
    image: "containous/whoami"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.newproject.com`)"
        - "traefik.http.routers.whoami.entrypoints=web-secure"
        - "traefik.http.routers.whoami.tls=true"
# 使用中间件重定向https
        - "traefik.http.routers.whoami.middlewares=redirect-to-https"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
# # http认证，user:passwod
        # - "traefik.http.routers.traefik.middlewares=auth"
        # - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true