logLevel = "DEBUG"

#defaultEntryPoints = ["http", "https"]

# http请求都重定向到https
[entryPoints]
  [entryPoints.http]
    address = ":80"
#    [entryPoints.http.redirect]
#      entryPoint = "https"
  [entryPoints.https]
    address = ":443"

  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/traefik.com.crt"
      keyFile = "/ssl/traefik.com.key"
    [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/portainer.com.crt"
      keyFile = "/ssl/portainer.com.key"