version: '3.7'
services:
  mysql:
    image: mysql:5.6.35
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: mytest
      MYSQL_USER: mytest
      MYSQL_PASSWORD: mytest

    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - newproject
#    ports:
#      - "3306:3306"

networks:
  newproject:
    external: true
volumes:
  mysql_data:

